

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT NULL, 60.0, 'Crafting' FROM DUAL;

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 40.0, 'Forging' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Crafting';

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 40.0, 'Tailoring' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Crafting';

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 40.0, 'Woodworking' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Crafting';

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 20.0, 'Weapon Forging' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Forging';

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 20.0, 'Armour Forging' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Forging';

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 8.0, 'Sword Crafting' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Weapon Forging';

INSERT INTO gameDB.SKILL (ID_PARENT_SKILL, FL_DIFFICULTY, ST_NAME)
SELECT S.ID_SKILL, 8.0, 'Dagger Crafting' FROM gameDB.SKILL S WHERE S.ST_NAME = 'Weapon Forging';


/**************************************************************************/


INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Object');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Stackable');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Resource');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Metal');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Weapon');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Meele Weapon');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Tin');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Copper');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Iron');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Steel');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Titanium');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Mithril');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Dagger');
INSERT INTO gameDB.ITEM_TYPE (ST_NAME) VALUES ('Sword');

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Object'
   AND C.ST_NAME = 'Stackable';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Object'
   AND C.ST_NAME = 'Resource';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Stackable'
   AND C.ST_NAME = 'Metal';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Resource'
   AND C.ST_NAME = 'Metal';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Object'
   AND C.ST_NAME = 'Weapon';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Weapon'
   AND C.ST_NAME = 'Meele Weapon';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Metal'
   AND C.ST_NAME = 'Tin';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Metal'
   AND C.ST_NAME = 'Copper';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Metal'
   AND C.ST_NAME = 'Iron';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Metal'
   AND C.ST_NAME = 'Steel';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Metal'
   AND C.ST_NAME = 'Titanium';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Metal'
   AND C.ST_NAME = 'Mithril';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Meele Weapon'
   AND C.ST_NAME = 'Dagger';

INSERT INTO gameDB.ITEM_TYPE_HIERARCHY (ID_ITEM_TYPE_PARENT, ID_ITEM_TYPE_CHILD)
SELECT P.ID_ITEM_TYPE, C.ID_ITEM_TYPE
  FROM gameDB.ITEM_TYPE P, gameDB.ITEM_TYPE C
 WHERE P.ST_NAME = 'Meele Weapon'
   AND C.ST_NAME = 'Sword';

INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT I.ID_ITEM_TYPE, 0, 0, 10, NULL, NULL, NULL, 'craft.multiplier'
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Tin';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT I.ID_ITEM_TYPE, 0, 0, 14, NULL, NULL, NULL, 'craft.multiplier'
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Copper';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT I.ID_ITEM_TYPE, 0, 0, 17, NULL, NULL, NULL, 'craft.multiplier'
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Iron';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT I.ID_ITEM_TYPE, 0, 0, 20, NULL, NULL, NULL, 'craft.multiplier'
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Steel';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT I.ID_ITEM_TYPE, 0, 0, 41, NULL, NULL, NULL, 'craft.multiplier'
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Titanium';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT I.ID_ITEM_TYPE, 0, 0, 110, NULL, NULL, NULL, 'craft.multiplier'
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Mithril';


/**************************************************************************/


INSERT INTO gameDB.RECIPE (ID_SKILL, ID_ITEM_TYPE, ST_NAME)
SELECT S.ID_SKILL, I.ID_ITEM_TYPE, I.ST_NAME
  FROM gameDB.SKILL S, gameDB.ITEM_TYPE I
 WHERE S.ST_NAME = 'Dagger Crafting'
   AND I.ST_NAME = 'Dagger';

INSERT INTO gameDB.RECIPE (ID_SKILL, ID_ITEM_TYPE, ST_NAME)
SELECT S.ID_SKILL, I.ID_ITEM_TYPE, I.ST_NAME
  FROM gameDB.SKILL S, gameDB.ITEM_TYPE I
 WHERE S.ST_NAME = 'Sword Crafting'
   AND I.ST_NAME = 'Sword';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT R.ID_RECIPE, 1, 0, 3, NULL, NULL, NULL, 'resources.needed'
  FROM gameDB.RECIPE R WHERE R.ST_NAME = 'Dagger';
  
INSERT INTO gameDB.PROPERTY (ID_OWNER, ID_OWNER_TYPE, ID_PROPERTY_TYPE, NB_VALUE, FL_VALUE, DT_VALUE, ST_VALUE, ST_NAME)
SELECT R.ID_RECIPE, 1, 0, 12, NULL, NULL, NULL, 'resources.needed'
  FROM gameDB.RECIPE R WHERE R.ST_NAME = 'Sword';


/**************************************************************************/


INSERT INTO gameDB.PLAYER (ST_NAME, NB_MAX_ENERGY, NB_ENERGY, NB_MONEY, ID_MODIFIED_BY)
VALUES ('Smith', 100, 100, 10000, 0);


/**************************************************************************/



INSERT INTO gameDB.PLAYER_SKILL (ID_PLAYER, ID_SKILL, FL_RATING, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, S.ID_SKILL, 1.0, 0
  FROM gameDB.PLAYER P, gameDB.SKILL S
 WHERE S.ST_NAME = 'Crafting'
   AND P.ST_NAME = 'Smith';

INSERT INTO gameDB.PLAYER_SKILL (ID_PLAYER, ID_SKILL, FL_RATING, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, S.ID_SKILL, 1.0, 0
  FROM gameDB.PLAYER P, gameDB.SKILL S
 WHERE S.ST_NAME = 'Forging'
   AND P.ST_NAME = 'Smith';

INSERT INTO gameDB.PLAYER_SKILL (ID_PLAYER, ID_SKILL, FL_RATING, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, S.ID_SKILL, 1.0, 0
  FROM gameDB.PLAYER P, gameDB.SKILL S
 WHERE S.ST_NAME = 'Weapon Forging'
   AND P.ST_NAME = 'Smith';

INSERT INTO gameDB.PLAYER_SKILL (ID_PLAYER, ID_SKILL, FL_RATING, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, S.ID_SKILL, 1.0, 0
  FROM gameDB.PLAYER P, gameDB.SKILL S
 WHERE S.ST_NAME = 'Dagger Crafting'
   AND P.ST_NAME = 'Smith';

INSERT INTO gameDB.PLAYER_SKILL (ID_PLAYER, ID_SKILL, FL_RATING, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, S.ID_SKILL, 1.0, 0
  FROM gameDB.PLAYER P, gameDB.SKILL S
 WHERE S.ST_NAME = 'Sword Crafting'
   AND P.ST_NAME = 'Smith';


/**************************************************************************/


INSERT INTO gameDB.PLAYER_RECIPE (ID_PLAYER, ID_RECIPE, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, R.ID_RECIPE, 0
  FROM gameDB.PLAYER P, gameDB.RECIPE R
 WHERE R.ST_NAME = 'Dagger'
   AND P.ST_NAME = 'Smith';

INSERT INTO gameDB.PLAYER_RECIPE (ID_PLAYER, ID_RECIPE, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, R.ID_RECIPE, 0
  FROM gameDB.PLAYER P, gameDB.RECIPE R
 WHERE R.ST_NAME = 'Sword'
   AND P.ST_NAME = 'Smith';


/**************************************************************************/


INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 10, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Tin';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 20, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Copper';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 50, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Iron';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 200, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Steel';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 1000, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Titanium';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 10000, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Mithril';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 1, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Dagger';

INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT 0, I.ID_ITEM_TYPE, I.ST_NAME, 1, 1, 0
  FROM gameDB.ITEM_TYPE I WHERE I.ST_NAME = 'Sword';
		


INSERT INTO gameDB.ITEM (ID_PLAYER, ID_ITEM_TYPE, ST_NAME, NB_QUANTITY, FL_VALUE, ID_MODIFIED_BY)
SELECT P.ID_PLAYER, I.ID_ITEM_TYPE, I.ST_NAME, 10, I.FL_VALUE, 0
  FROM gameDB.PLAYER P, gameDB.ITEM I
 WHERE P.ST_NAME = 'Smith' AND I.ST_NAME = 'Tin';


/**************************************************************************/


ANALYZE TABLE gameDB.SKILL;
ANALYZE TABLE gameDB.ITEM_TYPE;
ANALYZE TABLE gameDB.ITEM_TYPE_HIERARCHY;
ANALYZE TABLE gameDB.RECIPE;
ANALYZE TABLE gameDB.PLAYER;
ANALYZE TABLE gameDB.PLAYER_SKILL;
ANALYZE TABLE gameDB.PLAYER_RECIPE;
ANALYZE TABLE gameDB.ITEM;
ANALYZE TABLE gameDB.GAME_EVENT;
ANALYZE TABLE gameDB.PROPERTY;

